contact_links:
  - name: Discord
    about: Need to contact me? You can do so on Discord. @vospel#3329
  - name: Mastodon
    url: https://cyberplace.social/@vospel
    about: Don't have discord? Don't worry, I also have Mastodon
